import { beforeAll, describe, expect, it } from 'vitest'
import { runHarness } from '../src/runner/index.js'
import { cfg } from '../src/config/index.js'
import { GREEN_CONTAINER, containerEnvVar, containerRunning, currentImage, dbNameFromUrl } from '../src/stack/index.js'
import { BACKEND, BLUE, GREEN, HaproxyClient } from '../src/haproxy/client.js'
import { report, resetStackTo } from './helpers.js'

/**
 * The target: the same upgrade, with no downtime.
 *
 * Judged under the `zero-downtime` policy, which permits subscription drops
 * (a websocket cannot be migrated across processes) but permits nothing else:
 * no failed requests, no incorrect results, no lost events, no missed
 * subscription rows.
 */
describe('zero-downtime upgrade — blue/green with cloned metadata', () => {
  beforeAll(async () => {
    await resetStackTo(cfg.fromVersion)
  }, 600_000)

  it('upgrades with no failed requests and no data loss', async () => {
    const result = await runHarness({
      profileName: 'default',
      policyName: 'zero-downtime',
      upgraderName: 'zero-downtime',
    })
    report('ZERO-DOWNTIME UPGRADE', result)

    const markers = result.scorecard.markers.map((m) => m.name)
    const h = result.scorecard.headline

    // Every gate must have been passed, in order. If the upgrade silently
    // skipped the verification gate, a green result would prove nothing.
    expect(markers).toContain('preflight.blue.ok')
    expect(markers).toContain('metadata.cloned')
    expect(markers).toContain('green.ready')
    expect(markers).toContain('green.verified')
    expect(markers).toContain('traffic.switch')
    expect(markers).toContain('drain.complete')
    expect(markers).toContain('upgrade.end')
    expect(markers).not.toContain('upgrade.aborted')

    // Green is genuinely serving the new version.
    expect(await containerRunning(GREEN_CONTAINER)).toBe(true)
    expect(await currentImage(GREEN_CONTAINER)).toBe(`hasura/graphql-engine:${cfg.toVersion}`)

    // Green boots against a CLONE, so blue's metadata database was never
    // migrated. That is what makes rollback a proxy flip rather than a repair.
    const greenMetaUrl = await containerEnvVar(GREEN_CONTAINER, 'HASURA_GRAPHQL_METADATA_DATABASE_URL')
    const greenMetaDb = dbNameFromUrl(greenMetaUrl)
    expect(greenMetaDb).toBeTruthy()
    expect(greenMetaDb).not.toBe(cfg.metadataDb)

    // The bar.
    expect(h.failedRequests).toBe(0)
    expect(h.longestContiguousOutageMs).toBe(0)
    expect(h.incorrectResults).toBe(0)
    expect(h.graphqlErrors).toBe(0)
    expect(h.lostEvents).toBe(0)
    expect(h.missedSubscriptionRows).toBe(0)

    // Cron events pre-generated by blue must have survived the clone and still
    // be firing on green. This is the specific thing cloning exists to protect.
    expect(result.scorecard.cron.scheduledEventsAtEnd ?? 0).toBeGreaterThan(0)
    expect(result.scorecard.cron.firesAfterUpgrade).toBeGreaterThan(0)

    // Enough load to make the zeroes meaningful.
    expect(result.scorecard.overall.requests).toBeGreaterThan(10_000)

    expect(result.verdict.violations).toEqual([])
    expect(result.verdict.pass).toBe(true)
  }, 1_800_000)

  it('leaves green as the only ready backend', async () => {
    const hap = new HaproxyClient(cfg.haproxyHost, cfg.haproxyPort)
    const stats = await hap.showStat()
    const green = stats.find((s) => s.pxname === BACKEND && s.svname === GREEN)
    const blue = stats.find((s) => s.pxname === BACKEND && s.svname === BLUE)
    expect(green?.status).toMatch(/^UP/)
    expect(blue?.status).not.toMatch(/^UP/)
  }, 120_000)
})
